sonar.projectKey=flui-demo-app
sonar.projectName=Flui Demo App
sonar.projectVersion=0.1.0

sonar.sources=src,scripts,public
sonar.exclusions=dist/**,node_modules/**,sql/**

sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
